// GENERATED by scripts/gen_kinds.py from the kernel's session-topology registration.
// Do not edit. Regenerate: uv run --project ../substrate python scripts/gen_kinds.py
// tests/test_envelope_kinds_generated_096.py fails when this file is stale.

/* eslint-disable no-restricted-syntax */
export const EnvelopeKind = {
  BackgroundTaskEnded: "BackgroundTaskEnded",
  FinalAnswer: "FinalAnswer",
  InjectionApplied: "substrate.InjectionApplied",
  InputBuildFailed: "substrate.InputBuildFailed",
  InterruptRequested: "InterruptRequested",
  ModelReply: "ModelReply",
  Park: "Park",
  PredicateQuarantined: "substrate.PredicateQuarantined",
  ProducerCancelled: "substrate.ProducerCancelled",
  ProducerCompleted: "substrate.ProducerCompleted",
  ProducerEmittedInvalidEvent: "substrate.ProducerEmittedInvalidEvent",
  ProducerFailed: "substrate.ProducerFailed",
  ProducerStarted: "substrate.ProducerStarted",
  PromptComposed: "PromptComposed",
  PromptFragment: "PromptFragment",
  RunFinalised: "substrate.RunFinalised",
  RunStarted: "substrate.RunStarted",
  SessionEndRequested: "SessionEndRequested",
  SessionEnded: "SessionEnded",
  SessionStarted: "SessionStarted",
  SessionWarning: "SessionWarning",
  TerminationMatched: "substrate.TerminationMatched",
  ToolCall: "ToolCall",
  ToolProgress: "ToolProgress",
  ToolResult: "ToolResult",
  TranscriptCompacted: "TranscriptCompacted",
  TriggerFired: "substrate.TriggerFired",
  UserMessage: "UserMessage",
} as const;

export type EnvelopeKindValue = typeof EnvelopeKind[keyof typeof EnvelopeKind];
