// GENERATED by scripts/gen_kinds.py from the kernel's status enums.
// Do not edit. Regenerate: uv run --project ../substrate python scripts/gen_kinds.py
// tests/test_envelope_kinds_generated_096.py fails when this file is stale.

/* eslint-disable no-restricted-syntax */
export const SessionStatus = {
  RUNNING: "running",
  PARKED: "parked",
  INTERRUPTED: "interrupted",
  ENDED: "ended",
} as const;

export type SessionStatusValue = typeof SessionStatus[keyof typeof SessionStatus];

export const TaskStatus = {
  RUNNING: "running",
  EXITED: "exited",
  STOPPED: "stopped",
} as const;

export type TaskStatusValue = typeof TaskStatus[keyof typeof TaskStatus];
