"""Generate web/vm/envelope_kinds.gen.ts from the kernel (Sprint 096).

The client used to hand-copy envelope kind strings (`web/vm/kinds.ts`); the copy drifted
(`"RunFinalised"` for the kernel's `"substrate.RunFinalised"`, Sep 23 to Oct 1) and the client
handled a kind no producer emits (`RateLimitedWaiting`). Hunt & Thomas, DRY: one authoritative
representation. The authority is the kernel's own registration of the session topology, read
through its public TopologyBuilder:

  - every schema a Producer kind registers (what Producers can emit),
  - every kind a Trigger or View subscribes to (what can be injected: UserMessage, ...),
  - every kind a topology injects without registering it (`tool_loop.INJECTED_EVENT_KINDS`),
  - every `substrate.*` lifecycle kind in `substrate.constants`.

Usage (source mode, from substrate-ui/):
  uv run --project ../substrate python scripts/gen_kinds.py          # write the file
  uv run --project ../substrate python scripts/gen_kinds.py --check  # exit 1 if stale
"""

from __future__ import annotations

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "web" / "vm" / "envelope_kinds.gen.ts"
# UI sprint 107: the kernel's status enums, which the client retyped as string-literal unions.
STATUS_OUT = Path(__file__).resolve().parent.parent / "web" / "vm" / "statuses.gen.ts"


def session_kinds() -> set[str]:
    import warnings

    from substrate import api, constants
    from substrate.reference import DeterministicResponder
    from substrate.topologies.session import session_topology
    from substrate.topologies.tool_loop import INJECTED_EVENT_KINDS

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")  # record_root=None warning: no run happens here
        topo = session_topology(
            driver=DeterministicResponder(0),
            driver_name="deterministic",
            driver_context_tokens=32768,
            seed="",
            tools={},
            session_id="s_generator",
            workspace_path="/nonexistent",
            bundle="session",
        )
    b = api.TopologyBuilder()
    topo(b)
    reg = b.build()
    kinds: set[str] = set()
    for pk in reg.producer_kinds.values():
        kinds.update(pk.schemas.keys())
    for t in reg.triggers:
        kinds.update(t.subscription.kinds)
    for v in reg.views.values():
        kinds.update(getattr(v.subscription, "kinds", ()) or ())
    kinds.update(t.__name__ for t in INJECTED_EVENT_KINDS)
    prefix = constants.RESERVED_PREFIX
    kinds.update(
        v
        for name, v in vars(constants).items()
        if name.isupper() and isinstance(v, str) and v.startswith(prefix) and v != prefix
    )
    return kinds


def render(kinds: set[str]) -> str:
    def key(k: str) -> str:
        return k.removeprefix("substrate.")

    keys = sorted(kinds, key=key)
    clash = {key(k) for k in keys if sum(1 for o in keys if key(o) == key(k)) > 1}
    if clash:
        raise SystemExit(
            f"gen_kinds: kind names collide once the substrate. prefix is dropped: {sorted(clash)}"
        )
    lines = [
        "// GENERATED by scripts/gen_kinds.py from the kernel's session-topology registration.",
        "// Do not edit. Regenerate: uv run --project ../substrate python scripts/gen_kinds.py",
        "// tests/test_envelope_kinds_generated_096.py fails when this file is stale.",
        "",
        "/* eslint-disable no-restricted-syntax */",
        "export const EnvelopeKind = {",
        *[f'  {key(k)}: "{k}",' for k in keys],
        "} as const;",
        "",
        "export type EnvelopeKindValue = typeof EnvelopeKind[keyof typeof EnvelopeKind];",
        "",
    ]
    return "\n".join(lines)


def render_statuses() -> str:
    """`SessionStatus` (a session manifest's status) and `TaskStatus` (a bash background task's),
    as `const` objects plus their value types."""
    from substrate.api import SessionStatus
    from substrate.topologies.tool_loop.background import TaskStatus

    lines = [
        "// GENERATED by scripts/gen_kinds.py from the kernel's status enums.",
        "// Do not edit. Regenerate: uv run --project ../substrate python scripts/gen_kinds.py",
        "// tests/test_envelope_kinds_generated_096.py fails when this file is stale.",
        "",
        "/* eslint-disable no-restricted-syntax */",
    ]
    for enum in (SessionStatus, TaskStatus):
        name = enum.__name__
        lines += [
            f"export const {name} = {{",
            *[f'  {m.name}: "{m.value}",' for m in enum],
            "} as const;",
            "",
            f"export type {name}Value = typeof {name}[keyof typeof {name}];",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    outputs = {OUT: render(session_kinds()), STATUS_OUT: render_statuses()}
    if "--check" in sys.argv:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        for p in stale:
            sys.stderr.write(f"gen_kinds: {p} is stale; regenerate it\n")
        return 1 if stale else 0
    for p, text in outputs.items():
        p.write_text(text)
        print(f"gen_kinds: wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
